apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: your-username/microservice1:latest
        ports:
        - containerPort: 3000
